version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: dev_test_postgres
    environment:
      POSTGRES_DB: dev_test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 3939:3939
    command: -p 3939

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dev_test_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4949
    ports:
      - 4949:4949
    depends_on:
      - postgres
